### ISSUE TITLE
奔溃

### ISSUE THREAD

**Issue by AnotherSkyBoy** [girish3/Vlog#2]
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid service notification: Notification(channel=Vlog pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 category=service vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by AnotherSkyBoy** [comment]
no manifest appication icon

**Comment by girish3** [comment]
Thanks, @AnotherSkyBoy for opening this issue. Let me know if you need any other help.
